migrateup:
	migrate -path pkg/db/migration -database "postgresql://postgres:Neebal@123@localhost:5432/gRPC_admission?sslmode=disable" -verbose up

migratedown:
	migrate -path pkg/db/migration -database "postgresql://postgres:Neebal@123@localhost:5432/gRPC_admission?sslmode=disable" -verbose down
