// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Admission struct {
	FullName        string         `json:"full_name"`
	ID              int32          `json:"id"`
	Gender          string         `json:"gender"`
	Dob             time.Time      `json:"dob"`
	Address         string         `json:"address"`
	PhoneNo         int32          `json:"phone_no"`
	PreviousCompany sql.NullString `json:"previous_company"`
	Designation     sql.NullString `json:"designation"`
	Skills          sql.NullString `json:"skills"`
}

type Login struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

type Registration struct {
	ID             int32     `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	FullName       string    `json:"full_name"`
	Email          string    `json:"email"`
	UpdatedAt      time.Time `json:"updated_at"`
	CreatedAt      time.Time `json:"created_at"`
}
