// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type TbAdmission struct {
	FullName        string         `json:"full_name"`
	ID              int32          `json:"id"`
	Gender          string         `json:"gender"`
	Dob             time.Time      `json:"dob"`
	Address         string         `json:"address"`
	PhoneNo         int32          `json:"phone_no"`
	PreviousCompany sql.NullString `json:"previous_company"`
	Designation     sql.NullString `json:"designation"`
	Skills          sql.NullString `json:"skills"`
}

type TbLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type TbRegistration struct {
	ID        int32          `json:"id"`
	Username  string         `json:"username"`
	FullName  string         `json:"full_name"`
	Email     sql.NullString `json:"email"`
	Password  string         `json:"password"`
	CreateAt  sql.NullTime   `json:"create_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
